name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  # - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  - pip=23.3.1
  - scikit-learn=1.3.2
  - mlflow=2.8.1
  - pip:
      # - mlflow==2.2.1
      - wandb==0.16.0



# name: train_random_forest
# channels:
#   - conda-forge
#   - defaults
# dependencies:
#   # - python=3.10
#   - hydra-core=1.3.2
#   - matplotlib=3.2.2
#   - pandas=1.1.4
#   - pip=20.3.3
#   - scikit-learn=0.24.1
#   - mlflow=2.2.1
#   - wandb=0.13.10
#   - pip:
#       # - wandb==0.10.21
